language: objective-c
osx_image: xcode9.2
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
   - SCAN_DEVICE="iPhone X (11.2)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone X (11.1)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 8 (11.0)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 7 (10.3)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 7 (10.2)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 7 (10.1)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 7 (10.0)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 6s (9.3)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 6s (9.2)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 6s (9.1)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 6s (9.0)" SCAN_SCHEME="Turducken"
   - SCAN_DEVICE="iPhone 6 (8.4)" SCAN_SCHEME="Turducken-no-UI-tests"
   - SCAN_DEVICE="iPhone 6 (8.3)" SCAN_SCHEME="Turducken-no-UI-tests"
   - SCAN_DEVICE="iPhone 6 (8.2)" SCAN_SCHEME="Turducken-no-UI-tests"
   - SCAN_DEVICE="iPhone 6 (8.1)" SCAN_SCHEME="Turducken-no-UI-tests"

   - SCAN_DEVICE="Apple TV 4K (11.2)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 4K (11.1)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 4K (11.0)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 1080p (10.2)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 1080p (10.1)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 1080p (10.0)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 1080p (9.2)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 1080p (9.1)" SCAN_SCHEME="TurduckenTV"
   - SCAN_DEVICE="Apple TV 1080p (9.0)" SCAN_SCHEME="TurduckenTV"

   - SCAN_DEVICE="arch=x86_64" SCAN_SCHEME="TurduckenMac"

install:
  - bundle update

script:
  - bundle exec fastlane scan
