language: objective-c
osx_image: xcode8.3
notifications:
  email: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
   - DESTINATION="OS=10.3,name=iPhone 7,platform=iOS Simulator" SCHEME="Clusterfuck"
   - DESTINATION="OS=10.1,name=iPhone 7,platform=iOS Simulator" SCHEME="Clusterfuck"
   - DESTINATION="OS=9.3,name=iPhone 6s,platform=iOS Simulator" SCHEME="Clusterfuck"
   - DESTINATION="OS=9.2,name=iPhone 6s,platform=iOS Simulator" SCHEME="Clusterfuck"
   - DESTINATION="OS=9.1,name=iPhone 6s,platform=iOS Simulator" SCHEME="Clusterfuck"
   - DESTINATION="OS=9.0,name=iPhone 6s,platform=iOS Simulator" SCHEME="Clusterfuck"
   - DESTINATION="OS=8.4,name=iPhone 6,platform=iOS Simulator" SCHEME="Clusterfuck-no-UI-tests"
   - DESTINATION="OS=8.3,name=iPhone 6,platform=iOS Simulator" SCHEME="Clusterfuck-no-UI-tests"
   - DESTINATION="OS=8.2,name=iPhone 6,platform=iOS Simulator" SCHEME="Clusterfuck-no-UI-tests"
   - DESTINATION="OS=8.1,name=iPhone 6,platform=iOS Simulator" SCHEME="Clusterfuck-no-UI-tests"

   - DESTINATION="OS=10.2,name=Apple TV 1080p,platform=tvOS Simulator" SCHEME="ClusterfuckTV"
   - DESTINATION="OS=10.1,name=Apple TV 1080p,platform=tvOS Simulator" SCHEME="ClusterfuckTV"
   - DESTINATION="OS=10.0,name=Apple TV 1080p,platform=tvOS Simulator" SCHEME="ClusterfuckTV"
   - DESTINATION="OS=9.2,name=Apple TV 1080p,platform=tvOS Simulator" SCHEME="ClusterfuckTV"
   - DESTINATION="OS=9.1,name=Apple TV 1080p,platform=tvOS Simulator" SCHEME="ClusterfuckTV"
   - DESTINATION="OS=9.0,name=Apple TV 1080p,platform=tvOS Simulator" SCHEME="ClusterfuckTV"

   - DESTINATION="arch=x86_64" SCHEME="ClusterfuckMac"

script:
  - xcodebuild test -project Clusterfuck.xcodeproj -scheme "${SCHEME}" -destination "${DESTINATION}"
